# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Storage contract for generated chart-data export artifacts."""

from __future__ import annotations

import os
from pathlib import Path
from typing import (
    BinaryIO,
    Iterable,
    Protocol,
    runtime_checkable,
    TYPE_CHECKING,
)
from uuid import UUID

from flask import current_app

from superset.utils.decorators import transaction

if TYPE_CHECKING:
    from superset.models.chart_data_export_artifact import ChartDataExportArtifact


@runtime_checkable
class ChartDataArtifactStore(Protocol):
    """Operator-provided durable storage for opaque export objects."""

    def write(self, key: str, chunks: Iterable[bytes]) -> int:
        """Atomically write chunks and return the persisted byte count."""

    def open(self, key: str) -> BinaryIO:
        """Open an artifact for binary reading."""

    def delete(self, key: str) -> None:
        """Delete an artifact if it exists."""


def validate_artifact_key(key: str) -> str:
    """Accept only canonical UUID object keys generated by the application."""
    parsed = UUID(key)
    if str(parsed) != key:
        raise ValueError("Artifact key must be a canonical UUID")
    return key


class FileSystemChartDataArtifactStore:
    """Atomic local-filesystem artifact store for single-host deployments."""

    def __init__(self, root: str | os.PathLike[str]) -> None:
        self._root = Path(root).resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        return self._root / validate_artifact_key(key)

    def write(self, key: str, chunks: Iterable[bytes]) -> int:
        target = self._path(key)
        temporary = target.with_suffix(".partial")
        size = 0
        try:
            descriptor = os.open(
                temporary,
                os.O_WRONLY | os.O_CREAT | os.O_EXCL,
                0o600,
            )
            with os.fdopen(descriptor, "wb") as output:
                for chunk in chunks:
                    output.write(chunk)
                    size += len(chunk)
                output.flush()
                os.fsync(output.fileno())
            os.replace(temporary, target)
            if directory_flag := getattr(os, "O_DIRECTORY", 0):
                directory = os.open(self._root, os.O_RDONLY | directory_flag)
                try:
                    os.fsync(directory)
                finally:
                    os.close(directory)
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise
        return size

    def open(self, key: str) -> BinaryIO:
        return self._path(key).open("rb")

    def delete(self, key: str) -> None:
        target = self._path(key)
        target.unlink(missing_ok=True)
        target.with_suffix(".partial").unlink(missing_ok=True)


def get_chart_data_artifact_store() -> ChartDataArtifactStore:
    """Return the configured store or fail closed on an invalid configuration."""
    store = current_app.config.get("CHART_DATA_ARTIFACT_STORE")
    if not isinstance(store, ChartDataArtifactStore):
        raise RuntimeError(
            "CHART_DATA_ARTIFACT_STORE must implement ChartDataArtifactStore"
        )
    return store


def delete_chart_data_export_artifact(
    artifact: ChartDataExportArtifact,
) -> None:
    """Delete the object before removing the metadata that addresses it."""
    from superset import db

    get_chart_data_artifact_store().delete(artifact.storage_key)
    db.session.delete(artifact)


@transaction()
def delete_chart_data_export_artifact_transactionally(
    artifact: ChartDataExportArtifact,
) -> None:
    """Delete object storage first and commit its metadata removal."""
    delete_chart_data_export_artifact(artifact)
